/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esport.tim;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import esport.config.Koneksi;
import esport.main.DashboardUtama;

/**
 *
 * @author ACER
 */
public class FrameTim extends javax.swing.JFrame {
    
    Connection conn;
    Statement st;
    ResultSet rs;
    PreparedStatement pst;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameTim.class.getName());

    /**
     * Creates new form FrameTim
     */
    public FrameTim() {
        initComponents();
        java.awt.Image icon = java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/esport/img/logo.png"));
        this.setIconImage(icon);
        this.setLocationRelativeTo(null); 
        koneksi();
        tampilData();
        kosongkanForm();
    }
    
    private void koneksi() {
        try {
            Koneksi kon = new Koneksi();
            conn = kon.conn;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal: " + e.getMessage());
        }
    }
    
    private boolean validasiForm() {
        if (txtNamaTim.getText().trim().isEmpty() || 
            txtAsalDaerah.getText().trim().isEmpty() || 
            txtNamaKapten.getText().trim().isEmpty() || 
            txtNoWa.getText().trim().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Harap lengkapi semua kolom data tim!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void kosongkanForm() {
        txtIdTim.setText("");
        txtNamaTim.setText("");
        txtAsalDaerah.setText("");
        txtNamaKapten.setText("");
        txtNoWa.setText("");
        txtNamaTim.requestFocus();
        
        btnSimpan.setEnabled(true);
        btnSimpan.setBackground(new java.awt.Color(20, 164, 77)); // Hijau
        btnUbah.setEnabled(false);
        btnUbah.setBackground(new java.awt.Color(153, 153, 153)); // Abu-abu
        btnHapus.setEnabled(false);
        btnHapus.setBackground(new java.awt.Color(153, 153, 153)); // Abu-abu
    }

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Tim");
        model.addColumn("Nama Tim");
        model.addColumn("Asal Daerah");
        model.addColumn("Nama Kapten");
        model.addColumn("No. WhatsApp");
        
        try {
            st = conn.createStatement();
            String sql = "SELECT * FROM tb_tim ORDER BY id_tim DESC";
            rs = st.executeQuery(sql);
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_tim"),
                    rs.getString("nama_tim"),
                    rs.getString("asal_daerah"),
                    rs.getString("nama_kapten"),
                    rs.getString("no_wa")
                });
            }
            tblTim.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Data: " + e.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (st != null) st.close();
            } catch (Exception e) {
                System.out.println("Gagal menutup resource: " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        panelInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdTim = new javax.swing.JTextField();
        txtNamaTim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAsalDaerah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNamaKapten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNoWa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnMainMenu = new javax.swing.JButton();
        panelTabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTim = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manajemen Tim Nextourey");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));

        lblJudul.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblJudul.setText("MANAJEMEN DATA TIM");

        panelInput.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID Tim :");

        txtIdTim.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama Tim :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Asal Daerah: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nama Kapten :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("No. WhatsApp :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Form Tim");

        btnUbah.setBackground(new java.awt.Color(217, 4, 22));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.setContentAreaFilled(false);
        btnUbah.setOpaque(true);
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(217, 4, 22));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 4, 22)));
        btnHapus.setContentAreaFilled(false);
        btnHapus.setMaximumSize(new java.awt.Dimension(72, 27));
        btnHapus.setMinimumSize(new java.awt.Dimension(72, 27));
        btnHapus.setOpaque(true);
        btnHapus.setPreferredSize(new java.awt.Dimension(72, 27));
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnBatal.setBackground(new java.awt.Color(0, 0, 0));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.setContentAreaFilled(false);
        btnBatal.setOpaque(true);
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        btnSimpan.setBackground(new java.awt.Color(20, 164, 77));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setContentAreaFilled(false);
        btnSimpan.setOpaque(true);
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        jPanel5.setBackground(new java.awt.Color(217, 4, 22));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelInputLayout.createSequentialGroup()
                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(20, 20, 20)
                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNamaKapten, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(txtAsalDaerah, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNamaTim, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIdTim, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNoWa)))
                        .addGroup(panelInputLayout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel9))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAsalDaerah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNamaKapten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNoWa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnSimpan)
                .addGap(20, 20, 20)
                .addComponent(btnUbah)
                .addGap(20, 20, 20)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnBatal)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnMainMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMainMenu.setText("KEMBALI\n");
        btnMainMenu.addActionListener(this::btnMainMenuActionPerformed);

        panelTabel.setBackground(new java.awt.Color(255, 255, 255));

        tblTim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Tim", "Nama Tim", "Asal Daerah", "Nama Kapten", "Nomor WA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTimMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTim);
        if (tblTim.getColumnModel().getColumnCount() > 0) {
            tblTim.getColumnModel().getColumn(0).setResizable(false);
            tblTim.getColumnModel().getColumn(1).setResizable(false);
            tblTim.getColumnModel().getColumn(2).setResizable(false);
            tblTim.getColumnModel().getColumn(3).setResizable(false);
            tblTim.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Tabel Data Tim");

        jPanel6.setBackground(new java.awt.Color(217, 4, 22));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelTabelLayout = new javax.swing.GroupLayout(panelTabel);
        panelTabel.setLayout(panelTabelLayout);
        panelTabelLayout.setHorizontalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTabelLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelTabelLayout.setVerticalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMainMenu)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(panelTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(lblJudul)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMainMenu)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        // TODO add your handling code here:
        DashboardUtama mainMenu = new DashboardUtama();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (!validasiForm()) {
            return; 
        }
        try {
            String sql = "INSERT INTO tb_tim (nama_tim, asal_daerah, nama_kapten, no_wa) VALUES (?, ?, ?, ?)";
            pst = conn.prepareStatement(sql);
            
            pst.setString(1, txtNamaTim.getText());
            pst.setString(2, txtAsalDaerah.getText());
            pst.setString(3, txtNamaKapten.getText());
            pst.setString(4, txtNoWa.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Tim Berhasil Disimpan!");
            tampilData();
            kosongkanForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menyimpan: " + e.getMessage());
        } finally {
            try { 
                if (pst != null) 
                    pst.close(); 
            } catch (Exception e) {
                System.out.println("Gagal menutup resource: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if (txtIdTim.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data tim di tabel yang akan dihapus!");
            return;
        }
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus Tim ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM tb_tim WHERE id_tim=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtIdTim.getText());
                
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Tim Berhasil Dihapus!");
                tampilData();
                kosongkanForm();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Menghapus: " + e.getMessage());
            } finally {
                try { 
                    if (pst != null) 
                        pst.close(); 
                } catch (Exception e) {
                    System.out.println("Gagal menutup resource: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        if (txtIdTim.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data tim di tabel yang akan diubah!");
            return;
        }
        if (!validasiForm()) {
            return; 
        }
        try {
            String sql = "UPDATE tb_tim SET nama_tim=?, asal_daerah=?, nama_kapten=?, no_wa=? WHERE id_tim=?";
            pst = conn.prepareStatement(sql);
            
            pst.setString(1, txtNamaTim.getText());
            pst.setString(2, txtAsalDaerah.getText());
            pst.setString(3, txtNamaKapten.getText());
            pst.setString(4, txtNoWa.getText());
            pst.setString(5, txtIdTim.getText()); // ID sebagai patokan (WHERE)
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Tim Berhasil Diubah!");
            tampilData();
            kosongkanForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Mengubah: " + e.getMessage());
        } finally {
            try { 
                if (pst != null) 
                    pst.close(); 
            } catch (Exception e) {
                System.out.println("Gagal menutup resource: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void tblTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTimMouseClicked
        // TODO add your handling code here:
        int baris = tblTim.rowAtPoint(evt.getPoint());
        if (baris != -1) {
            txtIdTim.setText(tblTim.getValueAt(baris, 0).toString());
            txtNamaTim.setText(tblTim.getValueAt(baris, 1).toString());
            txtAsalDaerah.setText(tblTim.getValueAt(baris, 2).toString());
            txtNamaKapten.setText(tblTim.getValueAt(baris, 3).toString());
            txtNoWa.setText(tblTim.getValueAt(baris, 4).toString());
            
            btnSimpan.setEnabled(false);
            btnSimpan.setBackground(new java.awt.Color(153, 153, 153));
            btnUbah.setEnabled(true);
            btnUbah.setBackground(new java.awt.Color(217, 4, 22)); // Merah
            btnHapus.setEnabled(true);
            btnHapus.setBackground(new java.awt.Color(255, 255, 255)); // Putih
        }
    }//GEN-LAST:event_tblTimMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        // Mengubah tema menjadi mirip Windows / OS bawaan
        javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(FrameTim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new FrameTim().setVisible(true); // Ganti nama frame-nya sesuai dengan nama file kamu
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelTabel;
    private javax.swing.JTable tblTim;
    private javax.swing.JTextField txtAsalDaerah;
    private javax.swing.JTextField txtIdTim;
    private javax.swing.JTextField txtNamaKapten;
    private javax.swing.JTextField txtNamaTim;
    private javax.swing.JTextField txtNoWa;
    // End of variables declaration//GEN-END:variables
}
