/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esport.match;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.SpinnerDateModel;
import javax.swing.JSpinner;
import esport.config.Koneksi;
import esport.main.DashboardUtama;
import java.awt.HeadlessException;
import java.sql.SQLException;

/**
 *
 * @author ACER
 */
public class FrameMatch extends javax.swing.JFrame {
    
    Connection conn;
Statement st;
ResultSet rs;
PreparedStatement pst;

String idMatch = "";

HashMap<String, Integer> mapTurnamen =
new HashMap<>();

HashMap<String, Integer> mapTim =
new HashMap<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameMatch.class.getName());

    /**
     * Creates new form FrameMatch
     */
    public FrameMatch() {
    initComponents();
    
    koneksi();
    
    spWaktu.setValue(new java.util.Date());
    JSpinner.DateEditor editor =
    new JSpinner.DateEditor(
    spWaktu,
    "dd/MM/yyyy HH:mm"
    );

    spWaktu.setEditor(editor);
    
    loadComboTurnamen();
    loadComboTim();
    
    btnUbah.setEnabled(false);
    btnHapus.setEnabled(false);
    
    tampilData();
    resetForm();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        panelInput3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbTurnamen = new javax.swing.JComboBox<>();
        cbTimA = new javax.swing.JComboBox<>();
        cbTimB = new javax.swing.JComboBox<>();
        txtBabak = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        spWaktu = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSkorA = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSkorB = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatch = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("MATCH");
        jLabel16.setToolTipText("");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        panelInput3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setText("Turnamen :");

        jLabel19.setText("Tim A :");

        jLabel20.setText("Tim B :");

        cbTurnamen.addActionListener(this::cbTurnamenActionPerformed);

        cbTimA.addActionListener(this::cbTimAActionPerformed);

        txtBabak.addActionListener(this::txtBabakActionPerformed);

        jLabel11.setText("Babak :");

        spWaktu.setModel(new javax.swing.SpinnerDateModel());

        jLabel12.setText("Waktu :");

        jLabel13.setText("Skor Tim A :");

        jLabel14.setText("Skor Tim B :");

        btnSimpan.setBackground(new java.awt.Color(20, 164, 77));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.setContentAreaFilled(false);
        btnSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSimpan.setOpaque(true);
        btnSimpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnUbah.setBackground(new java.awt.Color(217, 4, 22));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(242, 242, 242));
        btnUbah.setText("UBAH");
        btnUbah.setContentAreaFilled(false);
        btnUbah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUbah.setOpaque(true);
        btnUbah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(217, 4, 22));
        btnHapus.setText("HAPUS");
        btnHapus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 4, 22), 1, true));
        btnHapus.setContentAreaFilled(false);
        btnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHapus.setOpaque(true);
        btnHapus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnBatal.setBackground(new java.awt.Color(51, 51, 51));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("BATAL");
        btnBatal.setContentAreaFilled(false);
        btnBatal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBatal.setOpaque(true);
        btnBatal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("FORM MATCH");

        javax.swing.GroupLayout panelInput3Layout = new javax.swing.GroupLayout(panelInput3);
        panelInput3.setLayout(panelInput3Layout);
        panelInput3Layout.setHorizontalGroup(
            panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInput3Layout.createSequentialGroup()
                .addGroup(panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInput3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelInput3Layout.createSequentialGroup()
                                .addGroup(panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBabak)
                                    .addComponent(cbTurnamen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTimA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTimB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spWaktu, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(txtSkorA)))
                            .addGroup(panelInput3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(19, 19, 19)
                                .addComponent(txtSkorB))))
                    .addGroup(panelInput3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBatal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(12, 12, 12))
            .addGroup(panelInput3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInput3Layout.setVerticalGroup(
            panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInput3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbTurnamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cbTimA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbTimB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtBabak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(spWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSkorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtSkorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnUbah)
                .addGap(20, 20, 20)
                .addComponent(btnHapus)
                .addGap(20, 20, 20)
                .addComponent(btnBatal)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelInput3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBatal, btnHapus, btnSimpan, btnUbah});

        getContentPane().add(panelInput3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("TABLE MATCH");

        tblMatch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Turnamen", "Tim A", "Tim B", "Babak", "Waktu", "Skor A", "Skor B"
            }
        ));
        tblMatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMatchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMatch);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setText("KEMBALI");
        btnKembali.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnKembali.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKembali.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(406, Short.MAX_VALUE)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(438, 438, 438))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(8, 8, 8))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKembali)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 590, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void koneksi(){

    try {

        Koneksi kon = new Koneksi();
        conn = kon.conn;

    } catch (Exception e){

        JOptionPane.showMessageDialog(null, e);

    }

    }

    private void loadComboTurnamen(){

    try {

        String sql =
        "SELECT * FROM tb_turnamen";

        st = conn.createStatement();
        rs = st.executeQuery(sql);

        cbTurnamen.removeAllItems();

        while(rs.next()){

            int id = rs.getInt("id_turnamen");
    String nama = rs.getString("nama_turnamen");

    cbTurnamen.addItem(nama);

    mapTurnamen.put(nama, id);

        }

    } catch (Exception e){

        JOptionPane.showMessageDialog(null, e);

    }

    }
    
    private void loadComboTim(){

    try {

        String sql =
        "SELECT * FROM tb_tim";

        st = conn.createStatement();
        rs = st.executeQuery(sql);

        cbTimA.removeAllItems();
        cbTimB.removeAllItems();

        while(rs.next()){

            int id = rs.getInt("id_tim");
        String nama = rs.getString("nama_tim");

        cbTimA.addItem(nama);
        cbTimB.addItem(nama);

        mapTim.put(nama, id);

        }

    } catch (Exception e){

        JOptionPane.showMessageDialog(null, e);

    }

    }
    
    private void resetForm(){
        
    btnUbah.setEnabled(false);
    btnHapus.setEnabled(false);    
    
    txtBabak.setText("");
    txtSkorA.setText("");
    txtSkorB.setText("");
    spWaktu.setValue(new java.util.Date());
    tblMatch.clearSelection();
    idMatch = "";

    cbTurnamen.setSelectedIndex(0);

    }
    
    private boolean validasiForm(){

    if(txtBabak.getText().trim().isEmpty()){

        JOptionPane.showMessageDialog(
            this,
            "Babak wajib diisi!"
        );

        return false;
    }

    if(txtSkorA.getText().trim().isEmpty() ||
       txtSkorB.getText().trim().isEmpty()){

        JOptionPane.showMessageDialog(
            this,
            "Skor wajib diisi!"
        );

        return false;
    }

    try {

        int skorA =
            Integer.parseInt(txtSkorA.getText());

        int skorB =
            Integer.parseInt(txtSkorB.getText());

        if(skorA < 0 || skorB < 0){

            JOptionPane.showMessageDialog(
                this,
                "Skor tidak boleh negatif!"
            );

            return false;
        }

    } catch(NumberFormatException e){

        JOptionPane.showMessageDialog(
            this,
            "Skor harus berupa angka!"
        );

        return false;
    }

    return true;
    }
    
    private void tampilData(){

    DefaultTableModel model =
        new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Turnamen");
    model.addColumn("Tim A");
    model.addColumn("Tim B");
    model.addColumn("Babak");
    model.addColumn("Waktu");
    model.addColumn("Skor A");
    model.addColumn("Skor B");

    try {

        String sql =
    "SELECT m.id_match, " +
    "t.nama_turnamen, " +
    "ta.nama_tim AS tim_a, " +
    "tb.nama_tim AS tim_b, " +
    "m.babak, " +
    "m.waktu_tanding, " +
    "m.skor_tim_a, " +
    "m.skor_tim_b " +
    "FROM tb_match m " +
    "JOIN tb_turnamen t ON m.id_turnamen = t.id_turnamen " +
    "JOIN tb_tim ta ON m.id_tim_a = ta.id_tim " +
    "JOIN tb_tim tb ON m.id_tim_b = tb.id_tim";

        st = conn.createStatement();
        rs = st.executeQuery(sql);

        while(rs.next()){

           model.addRow(new Object[]{

        rs.getString("id_match"),
        rs.getString("nama_turnamen"),
        rs.getString("tim_a"),
        rs.getString("tim_b"),
        rs.getString("babak"),
        rs.getString("waktu_tanding"),
        rs.getString("skor_tim_a"),
        rs.getString("skor_tim_b")

        });

        }

        tblMatch.setModel(model);

    } catch (SQLException e){

        JOptionPane.showMessageDialog(null, e);

    }

    }
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(!validasiForm()){
    return;
}
    try {

        // Validasi ComboBox
        if(cbTurnamen.getSelectedItem() == null ||
           cbTimA.getSelectedItem() == null ||
           cbTimB.getSelectedItem() == null){

            JOptionPane.showMessageDialog(
                this,
                "Data turnamen atau tim belum tersedia!"
            );

            return;
        }

        // Ambil ID dari ComboBox
        String turnamen =
            cbTurnamen.getSelectedItem().toString();

        String timA =
            cbTimA.getSelectedItem().toString();

        String timB =
            cbTimB.getSelectedItem().toString();

        int idTurnamen =
        mapTurnamen.get(turnamen);

        int idTimA =
        mapTim.get(timA);

        int idTimB =
        mapTim.get(timB);

        // Validasi tim
        if(idTimA == idTimB){

            JOptionPane.showMessageDialog(
                this,
                "Tim A dan Tim B tidak boleh sama!"
            );

            return;
        }

        // Validasi skor
        int skorA =
            Integer.parseInt(txtSkorA.getText());

        int skorB =
            Integer.parseInt(txtSkorB.getText());

        // Query SQL
        String sql =
        "INSERT INTO tb_match "
        + "(id_turnamen,id_tim_a,id_tim_b,"
        + "babak,waktu_tanding,"
        + "skor_tim_a,skor_tim_b) "
        + "VALUES (?,?,?,?,?,?,?)";

        pst = conn.prepareStatement(sql);

        pst.setInt(1, idTurnamen);
        pst.setInt(2, idTimA);
        pst.setInt(3, idTimB);

        pst.setString(4, txtBabak.getText());

        // Ambil waktu dari spinner
        java.util.Date waktu =
            (java.util.Date) spWaktu.getValue();

        pst.setTimestamp(
            5,
            new java.sql.Timestamp(
                waktu.getTime()
            )
        );

        pst.setInt(6, skorA);
        pst.setInt(7, skorB);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(
            this,
            "Data Match Berhasil Disimpan"
        );

        tampilData();
        resetForm();

    } catch (NumberFormatException e){

        JOptionPane.showMessageDialog(
            this,
             e.getMessage()
        );

    } catch (Exception e){

        JOptionPane.showMessageDialog(
            this,
            e
        );

    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        if(!validasiForm()){
    return;
}
         try {

        if(idMatch.equals("")){

            JOptionPane.showMessageDialog(
                this,
                "Pilih data pada tabel terlebih dahulu!"
            );

            return;
        }

        int idTurnamen =
        mapTurnamen.get(
        cbTurnamen.getSelectedItem().toString()
    );

        int idTimA =
        mapTim.get(
        cbTimA.getSelectedItem().toString()
    );

        int idTimB =
        mapTim.get(
        cbTimB.getSelectedItem().toString()
    );
        String sql =
        "UPDATE tb_match SET "
        + "id_turnamen=?, "
        + "id_tim_a=?, "
        + "id_tim_b=?, "
        + "babak=?, "
        + "waktu_tanding=?, "
        + "skor_tim_a=?, "
        + "skor_tim_b=? "
        + "WHERE id_match=?";

        pst = conn.prepareStatement(sql);

        pst.setInt(1, idTurnamen);
        pst.setInt(2, idTimA);
        pst.setInt(3, idTimB);

        pst.setString(4, txtBabak.getText());

        java.util.Date waktu =
            (java.util.Date) spWaktu.getValue();

        pst.setTimestamp(
            5,
            new java.sql.Timestamp(
                waktu.getTime()
            )
        );

        pst.setInt(
            6,
            Integer.parseInt(txtSkorA.getText())
        );

        pst.setInt(
            7,
            Integer.parseInt(txtSkorB.getText())
        );

        pst.setString(8, idMatch);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(
            this,
            "Data berhasil diubah"
        );

        tampilData();
        resetForm();

        idMatch = "";

    } catch (Exception e){

        JOptionPane.showMessageDialog(this, e);

    }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if (idMatch.equals("")) {

        JOptionPane.showMessageDialog(this,
            "Pilih data yang ingin dihapus!");

    } else {

        int konfirmasi =
            JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus data?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
            );

        if (konfirmasi == JOptionPane.YES_OPTION) {

            try {

                String sql =
                    "DELETE FROM tb_match "
                    + "WHERE id_match=?";

                pst = conn.prepareStatement(sql);

                pst.setString(1, idMatch);

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,
                    "Data berhasil dihapus");

                tampilData();
                resetForm();

                idMatch = "";

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e);

            }

        }

    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        resetForm();

        idMatch = "";
        tblMatch.clearSelection();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void cbTurnamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTurnamenActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbTurnamenActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        DashboardUtama dashboard = new DashboardUtama();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void cbTimAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTimAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTimAActionPerformed

    private void txtBabakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBabakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBabakActionPerformed

    private void tblMatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMatchMouseClicked
        // TODO add your handling code here:
        btnUbah.setEnabled(true);
        btnHapus.setEnabled(true);

        try {

            int baris =
            tblMatch.getSelectedRow();

            idMatch =
            tblMatch.getValueAt(baris, 0).toString();

            cbTurnamen.setSelectedItem(
                tblMatch.getValueAt(baris, 1).toString()
            );

            cbTimA.setSelectedItem(
                tblMatch.getValueAt(baris, 2).toString()
            );

            cbTimB.setSelectedItem(
                tblMatch.getValueAt(baris, 3).toString()
            );

            txtBabak.setText(
                tblMatch.getValueAt(baris, 4).toString()
            );

            txtSkorA.setText(
                tblMatch.getValueAt(baris, 6).toString()
            );

            txtSkorB.setText(
                tblMatch.getValueAt(baris, 7).toString()
            );
            java.sql.Timestamp waktu =
            java.sql.Timestamp.valueOf(
                tblMatch.getValueAt(baris, 5).toString()
            );

            spWaktu.setValue(waktu);

        } catch (Exception e){

            JOptionPane.showMessageDialog(this, e);

        }
    }//GEN-LAST:event_tblMatchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            // Mengubah tema menjadi mirip Windows / OS bawaan
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FrameMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMatch().setVisible(true); // Ganti nama frame-nya sesuai dengan nama file kamu
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbTimA;
    private javax.swing.JComboBox<String> cbTimB;
    private javax.swing.JComboBox<String> cbTurnamen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelInput3;
    private javax.swing.JSpinner spWaktu;
    private javax.swing.JTable tblMatch;
    private javax.swing.JTextField txtBabak;
    private javax.swing.JTextField txtSkorA;
    private javax.swing.JTextField txtSkorB;
    // End of variables declaration//GEN-END:variables
}
