/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esport.registrasi;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import esport.config.Koneksi;
/**
 *
 * @author ACER
 */
public class FrameRegistrasi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameRegistrasi.class.getName());

    /**
     * Creates new form FrameRegistrasi
     */
    public FrameRegistrasi() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Panggil method ini
        tampilData();
        loadComboTurnamen();
        loadComboTim();
    }
    
    // 1. Method untuk menampilkan data ke jTable1 (JOIN 3 Tabel)
    private void tampilData() {
        Object header[] = {"ID Registrasi", "Nama Turnamen", "Nama Tim", "Tgl Daftar", "Status Bayar"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        tableData.setModel(data);
        
        try {
            Koneksi kon = new Koneksi();
            Statement st = kon.conn.createStatement();
            
            // Query JOIN 3 tabel
            String sql = "SELECT r.id_registrasi, t.nama_turnamen, tm.nama_tim, r.waktu_daftar, r.status_bayar " +
                         "FROM tb_registrasi r " +
                         "JOIN tb_turnamen t ON r.id_turnamen = t.id_turnamen " +
                         "JOIN tb_tim tm ON r.id_tim = tm.id_tim " +
                         "ORDER BY r.id_registrasi DESC";
                         
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                data.addRow(new Object[]{
                    rs.getString("id_registrasi"),
                    rs.getString("nama_turnamen"),
                    rs.getString("nama_tim"),
                    rs.getString("waktu_daftar"),
                    rs.getString("status_bayar")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Tampil Data: " + e.getMessage());
        }
    }

    // 2. Method untuk mengisi cmbTurnamen
    private void loadComboTurnamen() {
        cmbTurnamen.removeAllItems();
        cmbTurnamen.addItem("- Pilih Turnamen -");
        try {
            Koneksi kon = new Koneksi();
            Statement st = kon.conn.createStatement();
            // Hanya tampilkan turnamen yang statusnya pendaftaran buka
            ResultSet rs = st.executeQuery("SELECT nama_turnamen FROM tb_turnamen WHERE status = 'Pendaftaran Buka'");
            while (rs.next()) {
                cmbTurnamen.addItem(rs.getString("nama_turnamen"));
            }
        } catch (Exception e) {
            System.out.println("Error load turnamen: " + e.getMessage());
        }
    }

    // 3. Method untuk mengisi cmbTim
    private void loadComboTim() {
        cmbTim.removeAllItems();
        cmbTim.addItem("- Pilih Tim -");
        try {
            Koneksi kon = new Koneksi();
            Statement st = kon.conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nama_tim FROM tb_tim ORDER BY nama_tim ASC");
            while (rs.next()) {
                cmbTim.addItem(rs.getString("nama_tim"));
            }
        } catch (Exception e) {
            System.out.println("Error load tim: " + e.getMessage());
        }
    }

    // 4. Method untuk mereset inputan form
    private void kosongkanForm() {
        txtIdReg.setText("");
        cmbTurnamen.setSelectedIndex(0);
        cmbTim.setSelectedIndex(0);
        cmbBayar.setSelectedIndex(0);
        dateDaftar.setDate(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdReg = new javax.swing.JTextField();
        cmbTurnamen = new javax.swing.JComboBox<>();
        cmbBayar = new javax.swing.JComboBox<>();
        dateDaftar = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        cmbTim = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("ID Registrasi: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblJudul.setText("REGISTRASI TIM KE TURNAMEN");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("ID Registrasi            : ");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Pilih Turnamen         : ");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Status Bayar             : ");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Pilih Tim                   : ");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setText("Form Input");

        txtIdReg.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtIdReg.addActionListener(this::txtIdRegActionPerformed);

        cmbTurnamen.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cmbTurnamen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbBayar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cmbBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunas", "Pending" }));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Tanggal Daftar          :");

        cmbTim.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cmbTim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTim.addActionListener(this::cmbTimActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdReg)
                    .addComponent(cmbTurnamen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbBayar, 0, 245, Short.MAX_VALUE)
                    .addComponent(cmbTim, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(cmbTurnamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(cmbTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(cmbBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(dateDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(151, 151, 151))
        );

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setText("Tabel Data");

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Turnamen ", "Tim", "waktu_daftar", "status_bayar"
            }
        ));
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableData);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
        );

        btnSimpan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        btnUbah.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblJudul)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnSimpan)
                .addGap(115, 115, 115)
                .addComponent(btnUbah)
                .addGap(115, 115, 115)
                .addComponent(btnHapus)
                .addGap(115, 115, 115)
                .addComponent(btnBatal)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblJudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHapus)
                        .addComponent(btnBatal)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdRegActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void cmbTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTimActionPerformed

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
        String turnamen = cmbTurnamen.getSelectedItem().toString();
        String tim = cmbTim.getSelectedItem().toString();
        String statusBayar = cmbBayar.getSelectedItem().toString();
        
        if (turnamen.equals("- Pilih Turnamen -") || tim.equals("- Pilih Tim -")) {
            JOptionPane.showMessageDialog(this, "Pilih Turnamen dan Tim terlebih dahulu!");
            return;
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String tglDaftar = sdf.format(dateDaftar.getDate());
        
        try {
            Koneksi kon = new Koneksi();
            Statement st = kon.conn.createStatement();
            
            // Cari ID Turnamen
            ResultSet rsTurnamen = st.executeQuery("SELECT id_turnamen FROM tb_turnamen WHERE nama_turnamen = '" + turnamen + "'");
            rsTurnamen.next();
            String idTurnamen = rsTurnamen.getString("id_turnamen");
            
            // Cari ID Tim
            ResultSet rsTim = st.executeQuery("SELECT id_tim FROM tb_tim WHERE nama_tim = '" + tim + "'");
            rsTim.next();
            String idTim = rsTim.getString("id_tim");
            
            // Insert Data
            String sql = "INSERT INTO tb_registrasi (id_turnamen, id_tim, waktu_daftar, status_bayar) " +
                         "VALUES ('" + idTurnamen + "', '" + idTim + "', '" + tglDaftar + "', '" + statusBayar + "')";
            st.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(null, "Registrasi Berhasil!");
            tampilData();
            kosongkanForm();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Registrasi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        // TODO add your handling code here:
        int baris = tableData.getSelectedRow();
        if (baris != -1) {
            txtIdReg.setText(tableData.getValueAt(baris, 0).toString());
            cmbTurnamen.setSelectedItem(tableData.getValueAt(baris, 1).toString());
            cmbTim.setSelectedItem(tableData.getValueAt(baris, 2).toString());
            
            // Asumsi kolom 3 adalah tanggal (index mulai dari 0)
            try {
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse((String)tableData.getValueAt(baris, 3));
                dateDaftar.setDate(date);
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            cmbBayar.setSelectedItem(tableData.getValueAt(baris, 4).toString());
        }
    }//GEN-LAST:event_tableDataMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
        String id = txtIdReg.getText();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus dari tabel!");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin hapus data registrasi ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Koneksi kon = new Koneksi();
                Statement st = kon.conn.createStatement();
                st.executeUpdate("DELETE FROM tb_registrasi WHERE id_registrasi = '" + id + "'");
                
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                tampilData();
                kosongkanForm();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal Menghapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btnBatalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameRegistrasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbBayar;
    private javax.swing.JComboBox<String> cmbTim;
    private javax.swing.JComboBox<String> cmbTurnamen;
    private com.toedter.calendar.JDateChooser dateDaftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txtIdReg;
    // End of variables declaration//GEN-END:variables
}
