/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esport.registrasi;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import esport.config.Koneksi;
import esport.main.DashboardUtama;
/**
 *
 * @author ACER
 */
public class FrameRegistrasi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameRegistrasi.class.getName());

    /**
     * Creates new form FrameRegistrasi
     */
    public FrameRegistrasi() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Panggil method ini
        tampilData();
        loadComboTurnamen();
        loadComboTim();
    }
    
    // 1. Method untuk menampilkan data ke jTable1 (JOIN 3 Tabel)
    private void tampilData() {
        Object header[] = {"ID Registrasi", "Nama Turnamen", "Nama Tim", "Tgl Daftar", "Status Bayar"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        tableData.setModel(data);
        
        try {
            Koneksi kon = new Koneksi();
            Statement st = kon.conn.createStatement();
            
            // Query JOIN 3 tabel
            String sql = "SELECT r.id_registrasi, t.nama_turnamen, tm.nama_tim, r.waktu_daftar, r.status_bayar " +
                         "FROM tb_registrasi r " +
                         "JOIN tb_turnamen t ON r.id_turnamen = t.id_turnamen " +
                         "JOIN tb_tim tm ON r.id_tim = tm.id_tim " +
                         "ORDER BY r.id_registrasi DESC";
                         
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                data.addRow(new Object[]{
                    rs.getString("id_registrasi"),
                    rs.getString("nama_turnamen"),
                    rs.getString("nama_tim"),
                    rs.getString("waktu_daftar"),
                    rs.getString("status_bayar")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Tampil Data: " + e.getMessage());
        }
    }

    // 2. Method untuk mengisi cmbTurnamen
    private void loadComboTurnamen() {
        cmbTurnamen.removeAllItems();
        cmbTurnamen.addItem("- Pilih Turnamen -");
        try {
            Koneksi kon = new Koneksi();
            Statement st = kon.conn.createStatement();
            // Hanya tampilkan turnamen yang statusnya pendaftaran buka
            ResultSet rs = st.executeQuery("SELECT nama_turnamen FROM tb_turnamen WHERE status = 'Pendaftaran Buka'");
            while (rs.next()) {
                cmbTurnamen.addItem(rs.getString("nama_turnamen"));
            }
        } catch (Exception e) {
            System.out.println("Error load turnamen: " + e.getMessage());
        }
    }

    // 3. Method untuk mengisi cmbTim
    private void loadComboTim() {
        cmbTim.removeAllItems();
        cmbTim.addItem("- Pilih Tim -");
        try {
            Koneksi kon = new Koneksi();
            Statement st = kon.conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT DISTINCT nama_tim FROM tb_tim ORDER BY nama_tim ASC");
            while (rs.next()) {
                cmbTim.addItem(rs.getString("nama_tim"));
            }
        } catch (Exception e) {
            System.out.println("Error load tim: " + e.getMessage());
        }
    }

    // 4. Method untuk mereset inputan form
    private void kosongkanForm() {
        txtIdReg.setText("");
        cmbTurnamen.setSelectedIndex(0);
        cmbTim.setSelectedIndex(0);
        cmbBayar.setSelectedIndex(0);
        dateDaftar.setDate(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdReg = new javax.swing.JTextField();
        cmbTurnamen = new javax.swing.JComboBox<>();
        cmbBayar = new javax.swing.JComboBox<>();
        dateDaftar = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        cmbTim = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnKembali = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("ID Registrasi: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        lblJudul.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblJudul.setText("REGISTRASI TIM KE TURNAMEN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID Registrasi            : ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Pilih Turnamen         : ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Status Bayar             : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Pilih Tim                   : ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Form Registrasi");

        txtIdReg.setEditable(false);
        txtIdReg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdReg.addActionListener(this::txtIdRegActionPerformed);

        cmbTurnamen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTurnamen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbBayar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunas", "Belum Lunas" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tanggal Daftar          :");

        cmbTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTim.addActionListener(this::cmbTimActionPerformed);

        jPanel3.setBackground(new java.awt.Color(217, 4, 22));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        btnSimpan.setBackground(new java.awt.Color(20, 164, 77));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.setContentAreaFilled(false);
        btnSimpan.setOpaque(true);
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnUbah.setBackground(new java.awt.Color(217, 4, 22));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("EDIT");
        btnUbah.setContentAreaFilled(false);
        btnUbah.setOpaque(true);
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbahMouseClicked(evt);
            }
        });
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnBatal.setBackground(new java.awt.Color(0, 0, 0));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("BATAL");
        btnBatal.setContentAreaFilled(false);
        btnBatal.setOpaque(true);
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(217, 4, 22));
        btnHapus.setText("HAPUS");
        btnHapus.setContentAreaFilled(false);
        btnHapus.setOpaque(true);
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbBayar, javax.swing.GroupLayout.Alignment.LEADING, 0, 225, Short.MAX_VALUE)
                                    .addComponent(cmbTim, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbTurnamen, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdReg, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cmbTurnamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cmbTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cmbBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(dateDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(btnSimpan)
                .addGap(18, 18, 18)
                .addComponent(btnUbah)
                .addGap(18, 18, 18)
                .addComponent(btnHapus)
                .addGap(18, 18, 18)
                .addComponent(btnBatal)
                .addGap(18, 18, 18))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBatal, btnHapus, btnSimpan, btnUbah});

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Tabel Data Registrasi");

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Turnamen ", "Tim", "waktu_daftar", "status_bayar"
            }
        ));
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableData);

        jPanel6.setBackground(new java.awt.Color(217, 4, 22));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setText("KEMBALI");
        btnKembali.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKembali.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(lblJudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        DashboardUtama dashboard = new DashboardUtama();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
        String id = txtIdReg.getText();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus dari tabel!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Yakin hapus data registrasi ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Koneksi kon = new Koneksi();
                Statement st = kon.conn.createStatement();
                st.executeUpdate("DELETE FROM tb_registrasi WHERE id_registrasi = '" + id + "'");

                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                tampilData();
                kosongkanForm();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal Menghapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        // TODO add your handling code here:
        kosongkanForm();
        
        btnSimpan.setEnabled(true);
        btnSimpan.setBackground(new java.awt.Color(20, 164, 77)); // [20,164,77]
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnUbahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseClicked
        // TODO add your handling code here:
    String idReg = txtIdReg.getText();
    String turnamen = cmbTurnamen.getSelectedItem().toString();
    String tim = cmbTim.getSelectedItem().toString();
    String statusBayar = cmbBayar.getSelectedItem().toString();

    // Validasi
    if (idReg.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih data dari tabel terlebih dahulu!");
        return;
    }

    try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String tglDaftar = sdf.format(dateDaftar.getDate());

        Koneksi kon = new Koneksi();
        Statement st = kon.conn.createStatement();

        // Cari ID Turnamen
        ResultSet rsTurnamen = st.executeQuery(
            "SELECT id_turnamen FROM tb_turnamen WHERE nama_turnamen = '" + turnamen + "'"
        );
        rsTurnamen.next();
        String idTurnamen = rsTurnamen.getString("id_turnamen");

        // Cari ID Tim
        ResultSet rsTim = st.executeQuery(
            "SELECT id_tim FROM tb_tim WHERE nama_tim = '" + tim + "'"
        );
        rsTim.next();
        String idTim = rsTim.getString("id_tim");

        // Query UPDATE
        String sql = "UPDATE tb_registrasi SET "
                + "id_turnamen = '" + idTurnamen + "', "
                + "id_tim = '" + idTim + "', "
                + "waktu_daftar = '" + tglDaftar + "', "
                + "status_bayar = '" + statusBayar + "' "
                + "WHERE id_registrasi = '" + idReg + "'";

        st.executeUpdate(sql);

        JOptionPane.showMessageDialog(this, "Data Berhasil Diubah!");

        tampilData();
        kosongkanForm();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal Mengubah Data : " + e.getMessage());
    }
    }//GEN-LAST:event_btnUbahMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
        String turnamen = cmbTurnamen.getSelectedItem().toString();
        String tim = cmbTim.getSelectedItem().toString();
        String statusBayar = cmbBayar.getSelectedItem().toString();

        if (turnamen.equals("- Pilih Turnamen -") || tim.equals("- Pilih Tim -")) {
            JOptionPane.showMessageDialog(this, "Pilih Turnamen dan Tim terlebih dahulu!");
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String tglDaftar = sdf.format(dateDaftar.getDate());

        try {
            Koneksi kon = new Koneksi();
            Statement st = kon.conn.createStatement();

            // Cari ID Turnamen
            ResultSet rsTurnamen = st.executeQuery("SELECT id_turnamen FROM tb_turnamen WHERE nama_turnamen = '" + turnamen + "'");
            rsTurnamen.next();
            String idTurnamen = rsTurnamen.getString("id_turnamen");

            // Cari ID Tim
            ResultSet rsTim = st.executeQuery("SELECT id_tim FROM tb_tim WHERE nama_tim = '" + tim + "'");
            rsTim.next();
            String idTim = rsTim.getString("id_tim");

            // Insert Data
            String sql = "INSERT INTO tb_registrasi (id_turnamen, id_tim, waktu_daftar, status_bayar) " +
            "VALUES ('" + idTurnamen + "', '" + idTim + "', '" + tglDaftar + "', '" + statusBayar + "')";
            st.executeUpdate(sql);

            JOptionPane.showMessageDialog(null, "Registrasi Berhasil!");
            tampilData();
            kosongkanForm();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Registrasi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void cmbTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTimActionPerformed

    private void txtIdRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdRegActionPerformed

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        // TODO add your handling code here:
        int baris = tableData.getSelectedRow();
        if (baris != -1) {
            txtIdReg.setText(tableData.getValueAt(baris, 0).toString());
            cmbTurnamen.setSelectedItem(tableData.getValueAt(baris, 1).toString());
            cmbTim.setSelectedItem(tableData.getValueAt(baris, 2).toString());
            cmbBayar.setSelectedItem(tableData.getValueAt(baris, 4).toString());

            // Asumsi kolom 3 adalah tanggal (index mulai dari 0)
            try {
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse((String)tableData.getValueAt(baris, 3));
                dateDaftar.setDate(date);
            } catch (Exception e) {
                e.printStackTrace();
            }

            
            btnSimpan.setEnabled(false);
            btnSimpan.setBackground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_tableDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            // Mengubah tema menjadi mirip Windows / OS bawaan
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FrameRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRegistrasi().setVisible(true); // Ganti nama frame-nya sesuai dengan nama file kamu
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbBayar;
    private javax.swing.JComboBox<String> cmbTim;
    private javax.swing.JComboBox<String> cmbTurnamen;
    private com.toedter.calendar.JDateChooser dateDaftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txtIdReg;
    // End of variables declaration//GEN-END:variables
}
